project:
  type: website

website:
  title: "What increases the liklihood of Kobe Passing the ball"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - model.qmd
      - sources.qmd
      - analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




